[package]
name = "testcrate"
version = "0.0.0"
edition = "2024"
publish = false

[features]
const_support = ["awint/const_support"]
gen_counter_for_pstate = ["awint/gen_counter_for_pstate"]
u32_for_pstate = ["awint/u32_for_pstate"]

[dependencies]
# the "debug" feature enabled here is a test for the flag and the generation counters it enables
awint = { workspace = true, features = ["rand_support", "serde_support", "zeroize_support", "dag", "debug", "std"] }

[build-dependencies]
awint = { workspace = true, features = ["std", "rand_support"] }
rand_xoshiro = { workspace = true }

[dev-dependencies]
# enable all other features here so that building on stable works
awint = { workspace = true, features = ["rand_support", "serde_support", "zeroize_support", "dag", "debug", "std", "try_support"] }
rand_xoshiro = { workspace = true }
ron = { workspace = true }
zeroize = { workspace = true }
