[workspace]
resolver = "2"
members = [
    "awint",
    "awint_core",
    "awint_dag",
    "awint_ext",
    "awint_macros",
    "awint_internals",
    "awint_macro_internals",
    "binaries",
    "testcrate",
]
