[workspace]
resolver = "2"
members = [
    "awint",
    "awint_core",
    "awint_dag",
    "awint_ext",
    "awint_internals",
    "awint_macro_internals",
    "awint_macros",
    "testcrate",
]

[patch.crates-io]
