[workspace]
resolver = "3"
members = [
    "awint",
    "awint_core",
    "awint_dag",
    "awint_ext",
    "awint_internals",
    "awint_macro_internals",
    "awint_macros",
    # note: this must be a separate workspace
    #"no_alloc_test",
    "testcrate",
]

[workspace.dependencies]
awint = { path = "./awint", default-features = false }
awint_core = { path = "./awint_core", default-features = false }
awint_dag = { path = "./awint_dag", default-features = false }
awint_ext = { path = "./awint_ext", default-features = false }
awint_internals = { path = "./awint_internals", default-features = false }
awint_macro_internals = { path = "./awint_macro_internals", default-features = false }
awint_macros = { path = "./awint_macros", default-features = false }
const_fn = "0.4"
proc-macro2 = "1.0"
rand_core = { version = "0.10", default-features = false }
rand_xoshiro = "0.8"
ron = "0.12"
serde = { version = "1", default-features = false }
smallvec = { version = "1.13", default-features = false, features = ["const_generics", "const_new", "union"] }
triple_arena = "0.15"
triple_arena_render = { version = "0.15" }
zeroize = { version = "1", default-features = false }

[patch.crates-io]
#triple_arena = { path = "../triple_arena/triple_arena" }
#triple_arena_render = { path = "../triple_arena/triple_arena_render" }
