[package]
name = "awint_internals"
version = "0.18.1"
edition = "2024"
# when updating, update `rust-msrv` in flake.nix and `stable_build` in ci.yml, and separately
# bump rust-toolchain.toml
rust-version = "1.85"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/awint"
description = "Internal utilities for the `awint` system of crates"

[features]
const_support = []
# Only zero or one of these should be active
u8_digits = []
u16_digits = []
u32_digits = []
u64_digits = []
u128_digits = []

[dependencies]
const_fn = "0.4"
