[package]
name = "awint_core"
version = "0.19.0"
edition = "2024"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/awint"
documentation = "https://docs.rs/awint"
description = "Core no-std and no-alloc `awint` functionality"
keywords = ["int", "integer", "big", "math", "no_std"]
categories = ["data-structures", "mathematics", "algorithms", "no-std"]

[features]
default = []
# Turns on nightly features required for many functions to be marked `const`
const_support = ["awint_internals/const_support"]
# Turns on `rand` support
rand_support = ["rand_core"]
# Turns on `serde` support
serde_support = ["serde"]
zeroize_support = ["zeroize"]
star_rng_support = ["star_rng"]
# Only zero or one of these should be active
u8_digits = ["awint_internals/u8_digits"]
u16_digits = ["awint_internals/u16_digits"]
u32_digits = ["awint_internals/u32_digits"]
u64_digits = ["awint_internals/u64_digits"]
u128_digits = ["awint_internals/u128_digits"]

[dependencies]
awint_internals = { workspace = true }
const_fn = { workspace = true }
rand_core = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
star_rng = { workspace = true, optional = true }
zeroize = { workspace = true, optional = true }

[dev-dependencies]
awint = { path = "../awint", default-features = false, features = ["alloc"] }
rand_xoshiro = { workspace = true }
ron = { workspace = true }
