[package]
name = "binaries"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "common"
path = "src/lib/common.rs"

[dependencies]
awint = { path = "../awint", default-features = false , features = ["dag"] }
awint_dag = { path = "../awint_dag" }
