[package]
name = "awint_dag"
version = "0.1.0-pre.0"
edition = "2018"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/AaronKutch/awint"
documentation = "https://docs.rs/awint"
description = "DAG `awint` functionality"
keywords = ["int", "integer", "big", "math", "no_std"]
categories = ["data-structures", "mathematics", "algorithms", "no-std"]

[dependencies]
awint_core = { version = "0.1.0-pre.0", path = "../awint_core" }
awint_ext = { version = "0.1.0-pre.0", path = "../awint_ext" }
awint_internals = { version = "0.1.0-pre.0", path = "../awint_internals" }

[dev-dependencies]
awint = { path = "../awint" }
