[package]
name = "awint_dag"
version = "0.6.0"
edition = "2021"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/awint"
documentation = "https://docs.rs/awint"
description = "DAG `awint` functionality"
keywords = ["int", "integer", "big", "math", "no_std"]
categories = ["data-structures", "mathematics", "algorithms", "no-std"]

[dependencies]
awint_core = { version = "0.6.0", path = "../awint_core", default-features = false }
awint_ext = { version = "0.6.0", path = "../awint_ext", default-features = false }
awint_internals = { version = "0.6.0", path = "../awint_internals", default-features = false }
awint_macros = { version = "0.6.0", path = "../awint_macros", default-features = false }
triple_arena = "0.6"
triple_arena_render = { version = "0.6", optional = true }

[features]
debug = ["triple_arena_render"]
