[package]
name = "awint_macro_internals"
version = "0.1.0-pre.0"
edition = "2018"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/AaronKutch/awint"
description = "Internal macro utilities for the `awint` system of crates"

[dependencies]
awint_core = { version = "0.1.0-pre.0", path = "../awint_core" }
awint_ext = { version = "0.1.0-pre.0", path = "../awint_ext" }

# for examples
[dev-dependencies]
awint = { path = "../awint" }
