[package]
name = "triple_arena"
version = "0.0.0"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
edition = "2018"

[dependencies]

[dev-dependencies]
rand_xoshiro = "0.6"

[features]
# Turns on `std` support
std = []
