name: Awint CI

on: [pull_request]

env:
  # NOTE: do not set RUSTFLAGS here, because it overwrites
  # what `.cargo/config.toml` sets for `no_alloc_build`
  RUST_BACKTRACE: 1

jobs:
  test_suite:
    name: Test suite
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust components
        run: |
          rustup set profile minimal
          rustup default nightly
      - name: Run test suite
        run: |
          cargo test --all-features
          cargo test --release --all-features

  miri:
    name: Miri
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install most recent Miri
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)"
          rustup component add miri
      - name: Run test suite with Miri
        run: |
          cargo miri test

  # we run `cargo doc` here, because running `cargo doc` anywhere somehow requires `core` from the
  # target in no_alloc_test
  no_alloc_build:
    name: Doc and Build for no-std and no-alloc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly-riscv32i-unknown-none-elf
        run: |
          rustup set profile minimal
          rustup default nightly
          rustup target add riscv32i-unknown-none-elf
      # no_alloc_test has `rand_support` and `serde_support` enabled in its `Cargo.toml`
      - name: Run `cargo doc` and `cargo build`
        run: |
          cargo doc --all-features
          cd no_alloc_test && cargo build --target riscv32i-unknown-none-elf

  stable_build:
    name: Build on stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust components
        run: |
          rustup set profile minimal
          rustup default stable
      # In the past I have had problems with features not being orthogonal due to configuration
      # mistakes, so we test several combinations here
      - name: Run `cargo build`
        run: |
          cargo build --no-default-features --features=std,rand_support,serde_support
          cargo build --no-default-features --features=std
          cargo build --no-default-features --features=rand_support
          cargo build --no-default-features --features=serde_support
          cargo build --no-default-features

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Acquire the most recent nightly with a rustfmt component
      - name: Install most recent Rustfmt
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/rustfmt)"
          rustup component add rustfmt
      - name: Run `cargo fmt`
        run: |
          cargo fmt -- --check
          cd no_alloc_test && cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Acquire the most recent nightly with a clippy component
      - name: Install most recent Clippy
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy)"
          rustup component add clippy
      - name: Run `cargo clippy`
        # note: run clippy on no_alloc_test manually
        run: |
          cargo clippy -- -D clippy::all
