name: Awint CI

on: [push, pull_request]

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1
  OUT_DIR: no_alloc_test/target/

jobs:
  test_suite:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust components
        run: |
          rustup set profile minimal
          rustup default nightly
      - name: Run test suite
        run: |
          cargo test --all-features
          cargo test --release --all-features

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install most recent Miri
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)"
          rustup component add miri
        # TODO run Miri from root when miri/issues/1813 and miri/issues/1311 are fixed
      - name: Run test suite with Miri
        run: |
          cd awint
          cargo miri test

  no_alloc_build:
    name: Build for no-std and no-alloc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly-riscv32i-unknown-none-elf
        run: |
          rustup set profile minimal
          rustup default nightly
          rustup target add riscv32i-unknown-none-elf
      - name: Run `cargo build`
        run: cd no_alloc_test && cargo build --target riscv32i-unknown-none-elf

  rustfmt:
    name: Rustfmt and Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Acquire the most recent nightly with a rustfmt component
      - name: Install most recent Rustfmt
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/rustfmt)"
          rustup component add rustfmt
      # `cargo doc` everything separately to avoid needing the target for no_alloc_build
      - name: Run `cargo fmt` and `cargo doc`
        run: |
          cargo fmt -- --check
          cd no_alloc_test && cargo fmt -- --check
          cargo doc -p awint_internals
          cargo doc -p awint_core
          cargo doc -p awint_ext
          cargo doc -p awint_macros
          cargo doc -p awint

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Acquire the most recent nightly with a clippy component
      - name: Install most recent Clippy
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy)"
          rustup component add clippy
      - name: Run `cargo clippy`
        # note: run clippy on no_alloc_test manually
        run: |
          cargo clippy -- -D clippy::all
